version: '3.8'

services:
  django:
    build: .
    image: django_app:latest
    container_name: django_app
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env  # Specifies the path to the .env file

  celery_worker:
    build: .
    image: django_app:latest
    container_name: celery_worker
    restart: always
    command: celery -A your_project_name worker --loglevel=info
    depends_on:
      - redis
      - django
    env_file:
      - .env

  celery_beat:
    build: .
    image: django_app:latest
    container_name: celery_beat
    restart: always
    command: celery -A your_project_name beat --loglevel=info
    depends_on:
      - redis
      - django
      - celery_worker
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"