version: '3.8'

services:
  django:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env  # Specifies the path to the .env file
  
  celery:
    build: .
    container_name: celery_worker
    command: celery -A your_project_name worker --loglevel=info
    depends_on:
      - redis
      - django
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:latest
    container_name: redis_broker
    ports:
      - "6379:6379"