version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A myproject worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A myproject beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"